### ISSUE TITLE
Product Features

### ISSUE THREAD

**Issue by ZeeshanAsghar173108** [ZeeshanAsghar173108/CourseRegistrationSystem#4]
will be performed by Usama Zafar

**Comment by Usamazafar266** [comment]
My task product features has been resolved.
[SAD Group Assignment No 1 Issue 4 resolved by Usama Zafar.docx](https://github.com/ZeeshanAsghar173108/CourseRegistrationSystem/files/6998769/SAD.Group.Assignment.No.1.Issue.4.resolved.by.Usama.Zafar.docx)
